//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Bao_Tang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HienVatXuatNhap
    {
        public string IDHienVatXuatNhap { get; set; }
        public string IDHienVat { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual HienVat HienVat { get; set; }
    }
}
