//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Bao_Tang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryNhanVIen
    {
        public string IDHistoryNhanVien { get; set; }
        public string IDNhanVien { get; set; }
        public Nullable<System.DateTime> NgayThemNhanVIen { get; set; }
        public Nullable<System.DateTime> NgayXoaNhanVien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
